name = "Shahrukh Mansuri"
rol = "Full Stack Developer"
email = "mansurishahrukh007@gmail.com"
phone = "+91 7405401426"
birthday = "August 15, 1996"
location = "Ahmedabad, Gujarat, India"
avatar = "./config/assets/avatars/my-avatar.png"
username = "shahrukh1426" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199666.5651251294!2d-121.58334177520186!3d38.56165006739519!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x809ac672b28397f9%3A0x921f6aaa74197fdb!2sSacramento%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1647608789441!5m2!1sen!2sbd"
presentation = """
Highly skilled Technical Lead with over 7 years of experience in full-stack development and project leadership. Adept at architecting and deploying scalable applications using modern technologies, with a strong emphasis on the MEAN stack (MongoDB, Express.js, Angular, and Node.js). 

Proven track record in developing complex systems, including real-time multiplayer games and blockchain-based solutions. Committed to continuous learning and fostering a collaborative team environment to drive innovation and excellence.
"""
