name = "Shahrukh Mansuri"
rol = "Full Stack Developer"
email = "mansurishahrukh007@gmail.com"
phone = "+91 740 540 1426"
birthday = "August 15, 1996"
location = "Ahmedabad, Gujarat, India"
avatar = "./config/assets/avatars/avatar.png"
username = "shahrukh1426" # <-- github user name
googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d199666.5651251294!2d-121.58334177520186!3d38.56165006739519!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x809ac672b28397f9%3A0x921f6aaa74197fdb!2sSacramento%2C%20CA%2C%20USA!5e0!3m2!1sen!2sbd!4v1647608789441!5m2!1sen!2sbd"
presentation = """
Results-driven Full Stack Developer with 7 years of experience designing, developing, and deploying scalable web applications. Proficient in front-end technologies (Angular, HTML, CSS) and back-end technologies (Node.js, Express). Experienced in working with databases (MongoDB, PostgreSQL) and implementing RESTful APIs. Skilled in DevOps practices using Docker and CI/CD tools. Adept at problem-solving and collaborating with cross-functional teams to deliver high-quality software solutions.
"""
