HEADER:
  label: "About me"

PRESENTATION:
  description: |
    Senior Civil Engineering student with diverse engineering project experience. Professional field experience as an Engineering Intern at Rockwell Automation and ASYST Technologies.
DOING:
  enabled: true
  label: "What I'm doing"
  items:
    - title: "UW-Milwaukee"
      icon: "config/assets/icons/mobile.svg"
      description: "B.S. in Civil Engineering - May 2026"
    - title: "Resident Assistant"
      icon: "config/assets/icons/code.svg"
      description: "Sandburg Resident Hall - North Tower Floor 24"
    - title: "Institute of Transportation of Engineers"
      icon: "config/assets/icons/compass.svg"
      description: "UW-Milwaukee Student Chapter - President"
    - title: "Filipino Student Union"
      icon: "config/assets/icons/laptop-code.svg"
      description: "UW-Milwaukee Student Organization - Treasurer"
