# We are using the ionicons icon set https://ionic.io/ionicons
# For example, to add a linkedin icon:
# <ion-icon name="logo-linkedin"></ion-icon>
# - icon: "logo-linkedin"

HEADER:
  label: "Show Contacts"

USER:
  role: "Civil Engineer"
  name: "James Ouano"
  username: "eagermace" # <-- This needs to be the same as your GitHub username
  avatar: "config/assets/avatars/ACVV3300L.jpg"

INFO:
  - label: "Email"
    value: "james.k.ouano@gmail.com"
    icon: "mail-outline"
  - label: "Phone"
    value: "+1 (847) 219-1491"
    icon: "phone-portrait-outline"
  - label: "Birthday"
    value: "July 31, 2003"
    icon: "calendar-outline"
  - label: "Location"
    value: "Milwaukee, WI"
    icon: "location-outline"

SOCIAL:
  - icon: "logo-facebook"
    url: "https://facebook.com/"
  - icon: "logo-twitter"
    url: "https://twitter.com/"
  - icon: "logo-instagram"
    url: "https://instagram.com/"
  - icon: "logo-linkedin"
    url: "https://www.linkedin.com/"
  - icon: "logo-github"
    url: "https://github.com/ivansaul"
  - icon: "logo-dribbble"
    url: "https://dribbble.com/"
