# [[project]]
# title = "Flutter Cinemapedia App"
# category = "Mobile development"
# image = "https://i.imgur.com/ANDVQ4o.png"
# url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"

# [[project]]
# title = "Flutter Coffee Shop App"
# category = "Mobile development"
# image = "https://imgur.com/2nNXhDN.png"
# url = "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

# [[project]]
# title = "Flutter Todo App"
# category = "Mobile development"
# image = "https://imgur.com/7110Lj1.png"
# url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

# [[project]]
# title = "Flutter Travel News App"
# category = "Mobile development"
# image = "https://imgur.com/t5T5Ixa.png"
# url = "https://github.com/ivansaul/flutter_travel_news_app#screenshots"

# [[project]]
# title = "Codigo Facilito Downloader"
# category = "Python Scripting"
# image = "https://imgur.com/kyHrBGk.png"
# url = "https://github.com/ivansaul/codigo_facilito_downloader"

# [[project]]
# title = "Finance"
# category = "Web development"
# image = "./config/assets/projects/project-1.jpg"
# url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"

# [[project]]
# title = "Orizon"
# category = "Web development"
# image = "./config/assets/projects/project-2.png"
# url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

# [[project]]
# title = "Fundo"
# category = "Web design"
# image = "./config/assets/projects/project-3.jpg"
# url = "https://github.com/ivansaul/flutter_cinemapedia_app#screenshots"

# [[project]]
# title = "Brawlhalla"
# category = "Applications"
# image = "./config/assets/projects/project-4.png"
# url = "https://github.com/ivansaul/flutter_coffee_shop_app#screenshots"

# [[project]]
# title = "DSM."
# category = "Web design"
# image = "./config/assets/projects/project-5.png"
# url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

# [[project]]
# title = "MetaSpark"
# category = "Web design"
# image = "./config/assets/projects/project-6.png"
# url = "https://github.com/ivansaul/flutter_todo_app#screenshots"

[[project]]
title = "SEVA my e-biz"
category = "Mobile development"
image = "./config/assets/projects/myebiz.png"
url = "https://play.google.com/store/apps/details?id=com.sevashop"

[[project]]
title = "SEVA MyMall"
category = "Mobile development"
image = "./config/assets/projects/mymall.png"
url = "https://play.google.com/store/apps/details?id=com.sevabiz.mall"

[[project]]
title = "SEVA Republic"
category = "Mobile development"
image = "./config/assets/projects/sevarepublic.png"
url = "https://play.google.com/store/apps/details?id=com.sevasathi"

[[project]]
title = "Uno Clash"
category = "Games"
image = "./config/assets/projects/unoclash.png"
url = "https://drive.google.com/file/d/1t4jPGlcbQKjfNlz9F2nm9QK1WbUVjknx/view?usp=drive_link"

[[project]]
title = "Ludo Empire"
category = "Games"
image = "./config/assets/projects/ludoempire.png"
url = "https://ludoempire.com"

[[project]]
title = "Cygnature"
category = "Web development"
image = "./config/assets/projects/cygnature.webp"
url = "https://www.cygnature.io"
