HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2017 — 2021"
      institution: "Warren Township High School"
      description: "Trident Robotics | National Honor Society | JV Tennis"
    - period: "2021 — 2022"
      institution: "Milwaukee School of Engineering"
      description: "Kapamilia Association – Vice President | Spike ball Club – Secretary"
    - period: "2022 — 2023"
      institution: "College of Lake County"
      description: "Engineering Club"
    - period: "2023 — Present"
      institution: "University of Wisconsin - Milwaukee"
      description: "Institute of Transportation Engineers – President | Filipino Student Union – Treasurer"

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "Aug 2024 — Present"
      position: "Resident Assistant"
      description: "Managing a college residence hall floor of undergraduate students, maintaining all bulletin boards and fliers with accurate, up-to-date, and useful information, and counseling students on various personal and academic issues."
    - period: "Jan 2024 - Jun 2024"
      position: "Water Surveys and Impact Analysis Intern"
      description: "Worked with The Water Council, various Rockwell Automation Departments, and other key stakeholders in creating a comprehensive water analysis for our HQ complex. The main project included reviewing and gathering data for all uses and discharges, reduction options assessment, and scenario analysis."
    - period: "May 2023 - Aug 2023"
      position: "Small Business Owner"
      description: "Implemented various marketing techniques and promotions to develop a loyal and growing customer base. Managed inventory, cost controls, and all aspects required to run a successful small business."
    - period: "Mar 2023 - Aug 2023"
      position: "Student Ambassador"
      description: "As an Enrollment Services Ambassador, I recruit new students to the College by providing campus tours, attending recruiting events, and assisting students virtually and on campus at the Welcome and One Stop Center."
    - period: "Jun 2022 - Aug 2022"
      position: "Mechanical Engineering Intern"
      description: "Gained valuable experience working in various departments at a cutting-edge company that produces injection molded components and engineered assemblies, allowing insight into the career and roles that engineers play within the automotive industry."      
    - period: "Mar 2022 - May 2022"
      position: "Student Representative"
      description: "MSOE challenges our team of students to come together & support the university and fellow students during our annual Giving Day period. We rally support for numerous areas of our campus or an Academic department of the donor's choice."
    - period: "Jan 2022 - Mar 2022"
      position: "Student Ambassador"
      description: "Responsible for contacting prospective students and families via outgoing phone calls, making outgoing phone calls, answering student questions & connecting students with admission counselors."
    - period: "Jun 2021 - Aug 2021"
      position: "Material Handler"
      description: "Worked in a team setting to reach warehouse operations goals, performing basic warehouse duties including shipping, packing, loading, and unloading trailers, reviewing work orders to ensure proper assembly, and accounting for all raw materials needed for the assembly of nail guns."
    - period: "Mar 2021 - Jun 2021"
      position: "Medical Tester"
      description: "Assembled and created swab test kits that nurses and CNA’s used to test individual patients. The kits are prepared in a clean room or similar laboratory. Reviewed work orders for proper assembly, and built test kits according to specifications."
LANGUAGES:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "Inglés"
      proficiency: "60%"
    - language: "Francés"
      proficiency: "40%"

SKILLS:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Web Design"
      proficiency: "80%"
    - skill: "Graphic Design"
      proficiency: "70%"
    - skill: "Branding"
      proficiency: "90%"
    - skill: "WordPress"
      proficiency: "50%"
