HEADER:
  label: "Resume"

EDUCATION:
  enabled: true
  label: "Education"
  items:
    - period: "2017 — 2021"
      institution: "Warren Township High School"
      description: "Trident Robotics | Gurnee Park District | National Honor Society | JV Tennis"
    - period: "2021 — 2022"
      institution: "Milwaukee School of Engineering"
      description: "Kapamilia Association – Vice President | Spike ball Club – Secretary"
    - period: "2022 — 2023"
      institution: "College of Lake County"
      description: "Engineering Club | Math Club"
    - period: "2023 — Present"
      institution: "University of Wisconsin - Milwaukee"
      description: "Institute of Transportation Engineers – President | Filipino Student Union – Treasurer"

EXPERIENCE:
  enabled: true
  label: "Experience"
  items:
    - period: "2010 — 2013"
      position: "Web Designer"
      description: "Worked on the design and development of websites for small to medium-sized businesses. Collaborated closely with developers to ensure responsive and user-friendly designs. Led the redesign of the company’s website, improving user engagement by 25%."
    - period: "2013 — 2015"
      position: "Art Director"
      description: "Led a team of designers to create visually stunning campaigns for major clients in the advertising industry. Managed the creative direction of print and digital media, ensuring consistent branding and high-quality designs. Oversaw the production of advertisements that won industry awards."
    - period: "2015 — Present"
      position: "Creative Director"
      description: "Direct and oversee the creative process for a range of projects, from concept to execution. Lead cross-functional teams to create innovative design solutions for branding, marketing, and digital experiences. Recently led the redesign of a global brand’s digital presence, increasing online sales by 40%."

LANGUAGES:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "Languages"
  items:
    - language: "Inglés"
      proficiency: "60%"
    - language: "Francés"
      proficiency: "40%"

SKILLS:
  enabled: false
  display_progress_bars: true
  display_percentage_values: true
  label: "My Skills"
  items:
    - skill: "Web Design"
      proficiency: "80%"
    - skill: "Graphic Design"
      proficiency: "70%"
    - skill: "Branding"
      proficiency: "90%"
    - skill: "WordPress"
      proficiency: "50%"
