############### Section config ##################
#################################################
title = "Tech Experience"
enabled = true # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[technologies]

git = "./config/assets/icons/git.svg"

mongodb = "./config/assets/icons/mongodb.svg"

html = "./config/assets/icons/html.svg"

linux = "./config/assets/icons/linux.svg"
