############### Section config ##################
#################################################
title = "Tech Experience"
enabled = true            # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[technologies]
html = "./config/assets/icons/color/html.svg"
css = "./config/assets/icons/color/css.svg"
javascript = "./config/assets/icons/color/javascript.svg"
typescript = "./config/assets/icons/color/typescript.svg"
angular = "./config/assets/icons/color/angular.svg"
rxjs = "./config/assets/icons/color/rxjs.svg"

expressjs = "./config/assets/icons/color/expressjs.svg"
nodejs = "./config/assets/icons/color/nodejs.svg"
socketio = "./config/assets/icons/color/socketio.svg"

jest = "./config/assets/icons/color/jest.svg"
mocha = "./config/assets/icons/color/mocha.svg"
chai = "./config/assets/icons/color/chai.svg"
karma = "./config/assets/icons/color/karma.svg"
jasmine = "./config/assets/icons/color/jasmine.svg"

mongodb = "./config/assets/icons/color/mongodb.svg"
postgresql = "./config/assets/icons/color/postgresql.svg"
mysql = "./config/assets/icons/color/mysql.svg"

redis = "./config/assets/icons/color/redis.svg"
rabbitmq = "./config/assets/icons/color/rabbitmq.svg"
kafka = "./config/assets/icons/color/kafka.svg"

elasticsearch = "./config/assets/icons/color/elasticsearch.svg"
logstash = "./config/assets/icons/color/logstash.svg"
kibana = "./config/assets/icons/color/kibana.svg"

docker = "./config/assets/icons/color/docker.svg"
kubernetes = "./config/assets/icons/color/kubernetes.svg"

git = "./config/assets/icons/color/git.svg"
github = "./config/assets/icons/color/github.svg"
gitlab = "./config/assets/icons/color/gitlab.svg"
bitbucket = "./config/assets/icons/color/bitbucket.svg"

aws = "./config/assets/icons/color/aws.svg"
digitalocean = "./config/assets/icons/color/digitalocean.svg"

jira = "./config/assets/icons/color/jira.svg"
basecamp = "./config/assets/icons/color/basecamp.svg"
trello = "./config/assets/icons/color/trello.svg"
