############### Section config ##################
#################################################
title = "Tech Experience"
enabled = true            # false

############### Technologies ####################
#################################################
# Technology I have worked with
# name = "./.../../icon_path"
[technologies]
html = "./config/assets/icons/color/html.svg"
css = "./config/assets/icons/color/css.svg"
javascript = "./config/assets/icons/color/javascript.svg"
angular = "./config/assets/icons/color/angular.svg"
karma = "./config/assets/icons/color/karma.svg"
kafka = "./config/assets/icons/color/kafka.svg"
bitbucket = "./config/assets/icons/color/bitbucket.svg"
digitalocean = "./config/assets/icons/color/digitalocean.svg"
expressjs = "./config/assets/icons/color/expressjs.svg"
gitlab = "./config/assets/icons/color/gitlab.svg"
jasmine = "./config/assets/icons/color/jasmine.svg"
jira = "./config/assets/icons/color/jira.svg"
kibana = "./config/assets/icons/color/kibana.svg"
mocha = "./config/assets/icons/color/mocha.svg"
nestjs = "./config/assets/icons/color/nestjs.svg"
prometheus = "./config/assets/icons/color/prometheus.svg"
rxjs = "./config/assets/icons/color/rxjs.svg"
typescript = "./config/assets/icons/color/typescript.svg"
aws = "./config/assets/icons/color/aws.svg"
chai = "./config/assets/icons/color/chai.svg"
docker = "./config/assets/icons/color/docker.svg"
git = "./config/assets/icons/color/git.svg"
grafana = "./config/assets/icons/color/grafana.svg"
kubernetes = "./config/assets/icons/color/kubernetes.svg"
mongodb = "./config/assets/icons/color/mongodb.svg"
nodejs = "./config/assets/icons/color/nodejs.svg"
rabbitmq = "./config/assets/icons/color/rabbitmq.svg"
socketio = "./config/assets/icons/color/socketio.svg"
basecamp = "./config/assets/icons/color/basecamp.svg"
elasticsearch = "./config/assets/icons/color/elasticsearch.svg"
github = "./config/assets/icons/color/github.svg"
jest = "./config/assets/icons/color/jest.svg"
logstash = "./config/assets/icons/color/logstash.svg"
mysql = "./config/assets/icons/color/mysql.svg"
postgresql = "./config/assets/icons/color/postgresql.svg"
redis = "./config/assets/icons/color/redis.svg"
trello = "./config/assets/icons/color/trello.svg"
